{
 "title": "Telepresence",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Number of connected traffic agents",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "agent_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of connected clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "client_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of active intercepts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_intercept_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of sessions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "session_count", "legendFormat": "__auto" }
   ]
  }
 ]
}