cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    deployment:
      accessible_namespaces: ["**"]
    external_services:
      prometheus:
        url: http://prometheus-server.monitoring.svc.cluster.local