cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    deployment:
      accessible_namespaces: ["**"]
    external_services:
      prometheus:
        url: http://prometheus-server.monitoring.svc.cluster.local
      tracing:
        enabled: true
        provider: jaeger
        in_cluster_url: http://jaeger-query.observability.svc.cluster.local:80
        url: http://jaeger-query.observability.svc.cluster.local:80