apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: istio-system
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 80
      protocol: TCP
      targetPort: 16686
    # Note: Change port name if you add '--query.grpc.tls.enabled=true'
    - name: grpc-query
      port: 16685
      protocol: TCP
      targetPort: 16685
  selector:
    app: jaeger

# apiVersion: v1
# kind: Service
# metadata:
#   name: jaeger-collector
#   namespace: istio-system
# spec:
#   selector:
#     app: jaeger
#   ports:
#     - name: zipkin
#       port: 9411
#       targetPort: 9411