#Jaeger implements the Zipkin API. To support swapping out the tracing backend, we use a Service named Zipkin.
apiVersion: v1
kind: Service
metadata:
  labels:
    name: zipkin
  name: zipkin
  namespace: istio-system
spec:
  ports:
    - port: 9411
      targetPort: 9411
      name: http-query
  selector:
    app: jaeger

# apiVersion: v1
# kind: Service
# metadata:
#   name: jaeger-query
#   namespace: istio-system
# spec:
#   selector:
#     app: jaeger
#   ports:
#     - name: ui
#       port: 16686
#       targetPort: 16686